export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const VALIDATION_ERROR = "VALIDATION_ERROR"
export const CLEAR_ERROR = "CLEAR_ERROR"
